/**
 * Media domain types
 *
 * Defines the structure of media entities and related types
 * for the Shopware 6 Admin API. Focused on BFSG compliance
 * (alt text management for accessibility).
 */

/**
 * Media thumbnail (auto-generated by Shopware)
 */
export interface MediaThumbnail {
  id: string;
  width: number;
  height: number;
  url: string;
}

/**
 * Media folder reference
 */
export interface MediaFolder {
  id: string;
  name: string;
}

/**
 * Product reference from media association
 */
export interface MediaProductReference {
  productId: string;
  productNumber: string;
  productName: string;
  active: boolean;
}

/**
 * Complete media entity with all details
 */
export interface Media {
  id: string;
  fileName: string;
  fileExtension: string;
  mimeType: string;
  fileSize: number;
  url: string | null;
  alt: string | null;
  title: string | null;
  mediaFolderId: string | null;
  folder: MediaFolder | null;
  thumbnails: MediaThumbnail[];
  products: MediaProductReference[];
  createdAt: string;
  updatedAt: string;
}

/**
 * Lightweight media for list views
 */
export interface MediaListItem {
  id: string;
  fileName: string;
  fileExtension: string;
  mimeType: string;
  fileSize: number;
  url: string | null;
  alt: string | null;
  title: string | null;
  createdAt: string;
}

/**
 * Media audit result item (media without alt text used on products)
 */
export interface MediaAuditItem {
  mediaId: string;
  fileName: string;
  url: string | null;
  alt: string | null;
  title: string | null;
  products: MediaProductReference[];
}

/**
 * Aggregated BFSG compliance audit result
 */
export interface MediaAuditResult {
  totalMediaChecked: number;
  missingAltCount: number;
  affectedProductCount: number;
  items: MediaAuditItem[];
}

/**
 * Result of media upload from URL
 */
export interface MediaUploadResult {
  success: boolean;
  mediaId: string;
  fileName: string;
  url: string | null;
}
